apiVersion: v2
name: rocketadmin
description: Rocketadmin is a web-based application for creating admin panels for your projects.
type: application
icon: https://avatars.githubusercontent.com/u/84132223
version: 1.0.16
home: https://rocketadmin.com
sources:
  - https://github.com/rocket-admin/rocketadmin
appVersion: "1.4.14"
dependencies:
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: "15.5.20"
  condition: "postgresql.enabled"
maintainers:
  - name: gugu
    email: andrii@rocketadmin.com
    url: https://rocketadmin.com
